export const ImageAssets = {
  logoApp: "/images/hewanku_logo.png",
  loginMockup: "/images/login_mockup.png",
  registerMockup: "/images/register_mockup.png",
  forgotPassMockup: "/images/forgot_pass_mockup.png",
  otpMockup: "/images/otp_mockup.png",
  setPassMockup: "/images/setPass_mockup.png",
  backgroundHeader: "/images/background_header.png",
  backgroundFooter: "/images/background_footer.png",
  qrisLogo: "/images/qris.png",
  mandiriLogo: "/images/mandiri.png",
  gopayLogo: "/images/gopay.png",
  danaLogo: "/images/dana.png",
  cat: "/images/cat.png",
  cat1: "/images/cat1.png",
  dog: "/images/dog.png",
  dog1: "/images/dog1.png",
  dog2: "/images/dog2.png",
  dog3: "/images/dog3.png",
  landak: "/images/landak.jpg",
  ikanMas: "/images/ikan_mas.png",
  kelinci: "/images/kelinci.png",
  ular: "/images/ular.jpeg",
  iguana: "/images/iguana.jpeg",
  hamster: "/images/hamster.jpeg",
  burung: "/images/burung.jpeg",
  burung1: "/images/burung1.png",
  kuraKura: "/images/kura_kura.jpeg",
};

export const IconAssets = {
  appleIcon: "/icons/apple_icon.svg",
  facebookIcon: "/icons/facebook_icon.svg",
  googleIcon: "/icons/google_icon.svg",
  back: "/icons/back.svg",
  facebookBlackIcon: "/icons/facebook.svg",
  instagramIcon: "/icons/instagram.svg",
  twitterIcon: "/icons/twitter.svg",
  youtubeIcon: "/icons/youtube.svg",
};
